language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
before_deploy:
  - yarn global add travis-ci-cloudfront-invalidation
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_DISTRIBUTION_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
